package clov.spellwords;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.File;
import java.io.FileReader;
import java.util.*;

public class ChatConfig {

    public static final File FILE = new File("config/chat_triggers.json");
    public static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public static ConfigData DATA = new ConfigData();

    public static void load() {
        try {
            if (!FILE.exists()) {
                FILE.getParentFile().mkdirs();
                DATA = createDefault();
                save();
                ClovMod.LOGGER.info("Created default config file at " + FILE.getAbsolutePath());
            }

            FileReader reader = new FileReader(FILE);
            DATA = GSON.fromJson(reader, ConfigData.class);
            reader.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void save() {
        try {
            java.io.FileWriter writer = new java.io.FileWriter(FILE);
            GSON.toJson(DATA, writer);
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // default config with example triggers
    private static ConfigData createDefault() {
        ConfigData data = new ConfigData();

        Trigger fireball = new Trigger();
            fireball.words = Arrays.asList("fireball");
            fireball.command = "execute as {player} at @s run summon fireball ~ ~1 ~ {ExplosionPower:0}";
            fireball.cooldownCommand = "tellraw {player} \"Wait {cooldown} seconds before using this spell again.\"";
            fireball.denyCommand = "tellraw {player} \"You are not a magician!\"";
            fireball.exactMatch = true;
            fireball.ignoreCase = true;
            fireball.cancelMessage = true;
            fireball.cooldownSeconds = 10;
            fireball.permission = "spellwords.fireball";

        Trigger banword = new Trigger();
            banword.words = Arrays.asList("badword","another badword","плохое слово");
            banword.command = "tellraw {player} \"Sorry, but that word is banned!\"";
            banword.exactMatch = false;
            banword.ignoreCase = true;
            banword.cancelMessage = true;
            banword.cooldownSeconds = 0;
            banword.runAsConsole = true;

        Trigger awadakadabra = new Trigger();
            awadakadabra.words = Arrays.asList("AvAdA kAdAbRa");
            awadakadabra.command = "kill {player}";
            awadakadabra.exactMatch = true;
            awadakadabra.ignoreCase = true;
            awadakadabra.cancelMessage = false;
            awadakadabra.cooldownSeconds = 0;
            awadakadabra.runAsConsole = true;
            awadakadabra.permission = "spellwords.awadakadabra";

        Trigger luckperms = new Trigger();
            luckperms.words = Arrays.asList("luckperms");
            luckperms.command = "tellraw {player} \"It seems you have permission to execute that command\"";
            luckperms.exactMatch = true;
            luckperms.ignoreCase = true;
            luckperms.cancelMessage = true;
            luckperms.cooldownSeconds = 0;
            luckperms.permission = "spellwords.luckperms";

        data.triggers.add(fireball);
        data.triggers.add(banword);
        data.triggers.add(awadakadabra);
        data.triggers.add(luckperms);

        return data;
    }


    // data classes for config ( I love VSCode for comment generation ( That comment was also generated by VSCode ) )

    public static class ConfigData {
        public List<Trigger> triggers = new ArrayList<>();
    }

    public static class Trigger {
        public List<String> words = new ArrayList<>(); // list of words that will activate this trigger
        public String command; // command to run when the trigger is activated, with {player} placeholder for the player's name
        public String cooldownCommand = ""; // command to run if the trigger is on cooldown, with {cooldown} placeholder for remaining seconds
        public String denyCommand = ""; // command to run if the player doesn't have permission ( honestly not sure if this is needed )

        public boolean exactMatch = false; // if true, the trigger will only activate if the chat message exactly matches one of the words; if false, it will activate if the chat message contains one of the words
        public boolean ignoreCase = true; // if true, word matching will ignore case (e.g. "Fireball" will match "fireball")
        public boolean cancelMessage = false; // if true, the original chat message will not be sent to other players

        public int cooldownSeconds = 0; // cooldown in seconds

        public boolean runAsConsole = false; // new field to specify if the command should be run as console ( basically as OP without needing the player to have permissions )

        public String permission = ""; // permission node required to trigger this command; if empty, no permission is required
    }
}